micronaut:
  application:
    name: HIVE-ETL

# Task Config
task:
  hive-path: '/user/hive/warehouse'
  hdfs-path: '/tmp/f2h'
  rawfile-path: '/rawfile'
  success-path: '/success'

# Database Config
datasources:
  default:
    url: jdbc:mysql://172.17.241.21:6033/BDP_PIPE
    username: BDP_PIPE
    password: "ENC(FE4L+6FbYoS7K73thhgSWW5kJ8f8wOB9)"
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        show_sql: false
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    entity-scan:
      packages: 'tw.com.taipeifubon.irisb.entities'

# Spark Configs
spark:
  log-level: 'ERROR'
  udf-package: 'tw.com.taipeifubon.irisb.udf'
  hive-root-path: '/user/hive/warehouse'

# Filesystem and HDFS Configs
hdfs:
  url: 'hdfs://nameservice1'
  kerberos:
    kdc: 'tpebnkbdpmh02t'
    user: 'bdpadmin@BDP.FBT.COM'
    realm: 'BDP.FBT.COM'
    keytab: '/opt/athemaster/principal/bdpadmin.keytab'
    pattern: 'hdfs/*@BDP.FBT.COM'

# FTP Server Configs
ftp:
  server1:
    host: 'localhost'
    port: 21
    path: '/f2h/'
    username: 'irisb'
    password: 'irisb'
  server2:
    host: 'localhost'
    port: 21
    path: '/f2h/'
    username: 'irisb'
    password: 'irisb'

# Jasypt Online Encryption
# https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
jasypt:
  encryptor:
    password: 'EJ2nfpo3SDFHIfalFJEKdcxx'